# Generated by Django 5.0.6 on 2024-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
